version: "3.3"

services:
    php-fpm:
        build: ./docker/php-fpm
        links:
            - db:db
        volumes:
            - ./:/var/www/html
            - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./docker/logs/php-fpm:/var/log/php-fpm

    nginx:
        image: nginx
        ports:
            - 80:80
        links:
            - php-fpm:php-fpm
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/logs/nginx:/var/log/nginx

    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/databases:/var/lib/mysql
            - ./docker/mysql/dump:/docker-entrypoint-initdb.d
            - ./docker/logs/mysql:/var/log/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 2G
        ports:
            - "8081:80"
        links:
            - db:db
